//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eJobsSmsManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.Recipients = new HashSet<Recipients>();
            this.Logs = new HashSet<Log>();
        }
    
        public int Id { get; set; }
        public string svcId { get; set; }
        public string Msg { get; set; }
        public string JobId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Recipients> Recipients { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
